const nums = s => s.split(",").map(x => parseFloat(x)).filter(Number.isFinite);
const mean = a => a.reduce((x, y) => x + y, 0) / a.length;

export const departments = [
  { id: "cse", code: "CSE", name: "Computer Science", color: "#2563EB",
    blurb: "Write code, break down problems, and check your logic against real test cases.",
    topics: ["Programming", "Logic building", "Problem solving", "Data structures"],
    tool: { type: "calc", title: "Number converter",
      hint: "Convert a decimal number to binary, octal and hex.",
      fields: [{ k: "n", label: "Decimal number", def: 45 }],
      out: [{ label: "Binary", fn: v => Number.isFinite(v.n) ? Math.trunc(v.n).toString(2) : NaN },
            { label: "Octal", fn: v => Number.isFinite(v.n) ? Math.trunc(v.n).toString(8) : NaN },
            { label: "Hex", fn: v => Number.isFinite(v.n) ? Math.trunc(v.n).toString(16).toUpperCase() : NaN }] } },
  { id: "ece", code: "ECE", name: "Electronics & Communication", color: "#7C3AED",
    blurb: "Work with circuits, signals, and the embedded ideas behind everyday devices.",
    topics: ["Circuit analysis", "Embedded concepts", "Signals", "Communication"],
    tool: { type: "calc", title: "Voltage divider",
      hint: "Vout = Vin × R2 / (R1 + R2)",
      fields: [{ k: "vin", label: "Input voltage", unit: "V", def: 12 }, { k: "r1", label: "R1", unit: "Ω", def: 1000 }, { k: "r2", label: "R2", unit: "Ω", def: 2200 }],
      out: [{ label: "Output voltage", unit: "V", fn: v => v.vin * v.r2 / (v.r1 + v.r2) },
            { label: "Current", unit: "mA", fn: v => v.vin / (v.r1 + v.r2) * 1000 }] } },
  { id: "mech", code: "MECH", name: "Mechanical", color: "#EA580C",
    blurb: "Understand forces, stress, and design choices through problems you can compute.",
    topics: ["Mechanics", "Machine design", "Materials", "Engineering problems"],
    tool: { type: "calc", title: "Stress in a round rod",
      hint: "Stress = Force / Area, with Area = π d² / 4",
      fields: [{ k: "f", label: "Axial force", unit: "N", def: 5000 }, { k: "d", label: "Diameter", unit: "mm", def: 20 }],
      out: [{ label: "Cross-section area", unit: "mm²", fn: v => Math.PI * v.d ** 2 / 4 },
            { label: "Stress", unit: "MPa", fn: v => v.f / (Math.PI * v.d ** 2 / 4) }] } },
  { id: "eee", code: "EEE", name: "Electrical & Electronics", color: "#A16207",
    blurb: "Practice power, machines, and control with the numbers engineers actually use.",
    topics: ["Power systems", "Electrical machines", "Control systems", "Instrumentation"],
    tool: { type: "calc", title: "Single-phase power",
      hint: "P = V × I × pf, and Q = V × I × sin φ",
      fields: [{ k: "v", label: "Voltage", unit: "V", def: 230 }, { k: "i", label: "Current", unit: "A", def: 5 }, { k: "pf", label: "Power factor", def: 0.8 }],
      out: [{ label: "Real power", unit: "W", fn: v => v.v * v.i * v.pf },
            { label: "Reactive power", unit: "VAR", fn: v => v.v * v.i * Math.sqrt(1 - v.pf ** 2) }] } },
  { id: "civil", code: "CIVIL", name: "Civil", color: "#15803D",
    blurb: "Test how structures carry load and make design calls before anything is built.",
    topics: ["Structures", "Construction", "Design loads", "Surveying"],
    tool: { type: "calc", title: "Simply supported beam",
      hint: "Reaction = wL / 2, and maximum moment = wL² / 8",
      fields: [{ k: "w", label: "Uniform load", unit: "kN/m", def: 10 }, { k: "l", label: "Span", unit: "m", def: 6 }],
      out: [{ label: "Support reaction", unit: "kN", fn: v => v.w * v.l / 2 },
            { label: "Maximum moment", unit: "kN·m", fn: v => v.w * v.l ** 2 / 8 }] } },
  { id: "ads", code: "AI&DS", name: "AI & Data Science", color: "#DB2777",
    blurb: "Explore data, learn what the numbers say, and build toward machine learning.",
    topics: ["Statistics", "Data analysis", "Machine learning", "Model thinking"],
    tool: { type: "calc", title: "Dataset summary",
      hint: "Enter numbers separated by commas.",
      fields: [{ k: "d", label: "Values", text: true, def: "4, 8, 15, 16, 23, 42" }],
      out: [{ label: "Mean", fn: v => mean(nums(v.d)) },
            { label: "Median", fn: v => { const a = nums(v.d).sort((x, y) => x - y); const m = a.length >> 1; return a.length % 2 ? a[m] : (a[m - 1] + a[m]) / 2; } },
            { label: "Std deviation", fn: v => { const a = nums(v.d); const m = mean(a); return Math.sqrt(mean(a.map(x => (x - m) ** 2))); } }] } },
];
