const A = (mid, title, q, ans, hint, sol, o = {}) => ({ kind: "ans", mid, title, q, ans, hint, sol, ...o });
const K = (mid, title, hint, sig, tests, trap, hints) => ({ kind: "code", mid, title, hint, starter: `function solve(${sig}) {\n  \n}`, tests, trap, hints });
const L = (title, place, icon, topic, diff, learn, challenges) => ({ title, place, icon, topic, diff, learn, challenges: challenges.map(c => ({ ...c, topic, level: diff })) });

export const missions = [
  { id: "parking", dept: "cse", icon: "🚗", title: "Smart Parking System",
    story: "The college parking lot has 20 slots and vehicles keep arriving. Build the brain of the parking system, one place at a time.",
    levels: [
      L("Basic conditions", "College Gate", "🚧", "Conditions", "Beginner",
        { text: "Conditions let your program decide. Use if / else and compare with >, >=, <, <= and ===. Be careful at the boundaries.", code: "function solve(temp) {\n  if (temp >= 30) return \"hot\";\n  return \"cool\";\n}" },
        [K("pk-1", "Is the gate open?", "The gate is open from 6 up to (not including) 22 o'clock. Write solve(hour) that returns \"open\" or \"closed\".", "hour", [[[5], "closed"], [[6], "open"], [[21], "open"], [[22], "closed"]], "Watch the boundaries: 6 is open and 22 is closed, so use >= and <.", ["Open means hour is at least 6 AND less than 22.", "if (hour >= 6 && hour < 22) return \"open\"; return \"closed\";"]),
         K("pk-2", "Is the lot full?", "The lot has 20 slots. Write solve(occupied) that returns \"full\" if occupied is 20 or more, otherwise \"free\".", "occupied", [[[20], "full"], [[0], "free"], [[19], "free"], [[25], "full"]], "Use >= and not ===, because the count can go above 20.", ["The lot is full when occupied reaches 20.", "return occupied >= 20 ? \"full\" : \"free\";"])]),
      L("Arrays", "Parking Lot", "🅿️", "Arrays", "Beginner",
        { text: "An array stores many values in order. Indexes start at 0. Use a loop to look at every slot. Here 0 means a free slot and 1 means an occupied slot.", code: "const slots = [1, 0, 1];\nslots[1];      // 0\nslots.length;  // 3\nfor (let i = 0; i < slots.length; i++) {\n  // look at slots[i]\n}" },
        [K("pk-3", "Count free slots", "Write solve(slots) that returns how many slots are free (value 0).", "slots", [[[[1, 0, 0, 1, 0]], 3], [[[1, 1]], 0], [[[0, 0, 0]], 3]], "Count only the 0 values, not the 1 values.", ["Loop through the array and count the zeros.", "let n = 0; for (const s of slots) if (s === 0) n++; return n;"]),
         K("pk-4", "First free slot", "Write solve(slots) that returns the index of the first free slot, or -1 if there is none.", "slots", [[[[1, 1, 0, 1]], 2], [[[0, 1]], 0], [[[1, 1]], -1]], "Return the index, not the value. Return -1 only after the loop ends.", ["Loop with an index and return it as soon as you see a 0.", "for (let i = 0; i < slots.length; i++) if (slots[i] === 0) return i; return -1;"])]),
      L("Queues", "Entry Lane", "🚙", "Queues", "Intermediate",
        { text: "A queue is First In, First Out. The first vehicle to arrive is the first one served. The front of the queue is queue[0].", code: "const q = [\"A\", \"B\", \"C\"];\nq[0];         // \"A\" is at the front\nq.slice(1);   // [\"B\", \"C\"] after serving A" },
        [K("pk-5", "Serve the next car", "Write solve(queue) that returns [servedCar, remainingQueue]. If the queue is empty return [null, []].", "queue", [[[["A", "B", "C"]], ["A", ["B", "C"]]], [[["X"]], ["X", []]], [[[]], [null, []]]], "A queue serves the FIRST item. Use queue[0] and queue.slice(1), not the last item.", ["The front is queue[0]. The rest is queue.slice(1).", "return [queue[0] ?? null, queue.slice(1)];"]),
         K("pk-6", "Park the queue", "Write solve(slots, queue) that returns how many waiting vehicles can be parked (0 = free slot).", "slots, queue", [[[[0, 0, 1], ["A", "B", "C"]], 2], [[[1, 1], ["A"]], 0], [[[0, 0, 0], ["A"]], 1]], "You cannot park more cars than free slots OR more than are waiting. Use the smaller number.", ["Count the free slots first, like in the Parking Lot.", "return Math.min(free, queue.length);"])]),
      L("Optimization", "Control Room", "🖥️", "Optimization", "Advanced",
        { text: "Optimization means choosing the best option. Look at every candidate, remember the best one so far, and replace it only when you find a better one.", code: "let best = -1;\nfor (let i = 0; i < arr.length; i++) {\n  if (/* i is better than best */) best = i;\n}" },
        [K("pk-7", "Nearest free slot", "The gate is at index g. Write solve(slots, g) that returns the free slot (0) closest to g. On a tie pick the lower index. Return -1 if none.", "slots, g", [[[[0, 1, 1, 0], 2], 3], [[[1, 0, 1, 0, 1], 0], 1], [[[1, 1, 1], 1], -1], [[[0, 0, 1, 0], 3], 3]], "Distance is Math.abs(i - g). Update your best slot only when the new distance is strictly smaller.", ["Check every free slot and measure Math.abs(i - g).", "Keep the best index so far and the best distance so far."]),
         K("pk-8", "Parking fee", "First hour costs 20, each extra hour costs 10, and the daily maximum is 100. 0 hours costs 0. Write solve(hours).", "hours", [[[1], 20], [[3], 40], [[10], 100], [[0], 0]], "Only the first hour costs 20. Cap the total at 100, and handle 0 hours first.", ["Handle 0 hours first. Then fee = 20 + 10 for each extra hour.", "if (hours === 0) return 0; return Math.min(100, 20 + (hours - 1) * 10);"])]),
    ] },
  { id: "light", dept: "ece", icon: "💡", title: "Smart Street Light",
    story: "The campus road is dark at night. Design a street light that switches on by itself using a light sensor (LDR).",
    levels: [
      L("Read the sensor", "Sensor Pole", "📡", "Sensors", "Beginner",
        { text: "An LDR has low resistance in daylight and high resistance in the dark. Put it in a voltage divider with a fixed resistor and the output voltage tells you how bright it is. Vout is measured across R2.", code: "Vout = Vin * R2 / (R1 + R2)" },
        [A("light-1", "Sensor in daylight", "In daylight the LDR (R1) is 1 kΩ and the fixed resistor (R2) is 4 kΩ. The supply is 5 V. Find Vout across R2 in volts.", "4", "Use Vout = Vin × R2 / (R1 + R2). Keep both resistors in kΩ.", "5 × 4 / (1 + 4) = 4 V. Bright light gives a high voltage."),
         A("light-2", "Sensor at night", "At night the LDR rises to 16 kΩ. R2 is still 4 kΩ and Vin is 5 V. Find Vout in volts.", "1", "Same formula, new R1 value.", "5 × 4 / (16 + 4) = 1 V. Darkness gives a low voltage.")]),
      L("Drive the lamp", "Lamp Head", "💡", "LED circuits", "Intermediate",
        { text: "An LED needs a series resistor so it does not burn out: R = (Vsupply - Vled) / I. Power lost in the resistor is P = I² × R. Use amps, not milliamps.", code: "R = (Vs - Vled) / I\nP = I * I * R" },
        [A("light-3", "LED resistor", "A 5 V supply drives an LED that drops 2 V and needs 20 mA. Find the series resistor in ohms.", "150", "R = (Vs − Vled) / I, with I = 0.02 A.", "(5 − 2) / 0.02 = 150 Ω."),
         A("light-4", "Resistor power", "How much power (in watts) does that 150 Ω resistor dissipate at 20 mA?", "0.06", "P = I² × R with I in amps.", "0.02² × 150 = 0.06 W, so a small 0.25 W resistor is fine.")]),
      L("Automatic control", "Control Box", "🎛️", "Control logic", "Advanced",
        { text: "A comparator turns the lamp ON when the sensor voltage falls below a threshold. Here the threshold is 2.5 V: below it means dark, so the lamp should be ON.", code: "if (vout < 2.5) return \"on\";\nreturn \"off\";" },
        [A("light-5", "Night decision", "The night reading from Level 1 was 1 V and the threshold is 2.5 V. Should the lamp be on or off? Type on or off.", "on", "Compare the reading with 2.5 V. Below the threshold means dark.", "1 V is below 2.5 V, so the lamp turns ON.", { text: true }),
         K("light-6", "Switch the light", "Write solve(vout) that returns \"on\" when vout is below 2.5, otherwise \"off\".", "vout", [[[1], "on"], [[4], "off"], [[2.5], "off"], [[2.49], "on"]], "At exactly 2.5 V the lamp stays off, so use < and not <=.", ["Use an if statement with vout < 2.5.", "return vout < 2.5 ? \"on\" : \"off\";"])]),
    ] },
  { id: "home", dept: "eee", icon: "🏠", title: "Power the Smart Home",
    story: "A home runs a water pump and has a solar panel. Work out the load, the bill, and build a smart meter.",
    levels: [
      L("Know your load", "Meter Board", "🔌", "Power", "Beginner",
        { text: "Real power is P = V × I × power factor. Energy is power × time: kWh = kW × hours.", code: "P = V * I * pf\nenergy(kWh) = P(kW) * hours" },
        [A("home-1", "Appliance power", "A pump runs on 230 V, draws 5 A, power factor 0.8. Find the real power in watts.", "920", "P = V × I × pf.", "230 × 5 × 0.8 = 920 W."),
         A("home-2", "Daily energy", "That 920 W pump runs for 5 hours. Find the energy in kWh.", "4.6", "Convert watts to kW first, then multiply by hours.", "0.92 kW × 5 h = 4.6 kWh.")]),
      L("Read the bill", "Billing Office", "🧾", "Energy cost", "Intermediate",
        { text: "Cost = energy (kWh) × tariff. Solar panels give energy too, so subtract what you generate.", code: "cost = kWh * rate\nsurplus = generated - used" },
        [A("home-3", "Energy cost", "The tariff is ₹6 per kWh. Find the cost of 4.6 kWh in rupees.", "27.6", "cost = kWh × rate.", "4.6 × 6 = ₹27.6."),
         A("home-4", "Solar surplus", "A 1.5 kW solar panel works 4 hours. How many kWh are left after the pump uses 4.6 kWh?", "1.4", "Generated = 1.5 × 4. Then subtract 4.6.", "1.5 × 4 = 6 kWh generated, and 6 − 4.6 = 1.4 kWh surplus.")]),
      L("Smart meter", "Control Panel", "📟", "Smart metering", "Advanced",
        { text: "Apparent power S = P / pf, measured in VA. A smart meter turns watts and hours into a bill automatically.", code: "S = P / pf" },
        [A("home-5", "Apparent power", "The pump uses 920 W at power factor 0.8. Find the apparent power in VA.", "1150", "S = P / pf.", "920 / 0.8 = 1150 VA."),
         K("home-6", "Smart meter bill", "Write solve(watts, hours, rate) that returns the bill: watts / 1000 × hours × rate.", "watts, hours, rate", [[[1000, 1, 6], 6], [[920, 5, 6], 27.6], [[500, 10, 8], 40], [[0, 5, 6], 0]], "Divide watts by 1000 to get kW before multiplying.", ["Convert watts to kW with watts / 1000.", "return watts / 1000 * hours * rate;"])]),
    ] },
  { id: "crane", dept: "mech", icon: "🏗️", title: "Safe Crane Lift",
    story: "A workshop crane must lift a 500 kg machine part. Check that the cable and the motor can do it safely.",
    levels: [
      L("Find the load", "Workshop Floor", "📦", "Forces", "Beginner",
        { text: "Weight is a force: W = m × g with g = 9.81 m/s². A round cable has area A = π d² / 4.", code: "W = m * 9.81\nA = Math.PI * d * d / 4" },
        [A("crane-1", "Weight of the load", "A crane lifts 500 kg. Find the weight in newtons (use g = 9.81).", "4905", "W = m × g.", "500 × 9.81 = 4905 N."),
         A("crane-2", "Cable area", "The steel cable has a diameter of 10 mm. Find its cross-section area in mm².", "78.54", "A = π d² / 4.", "π × 10² / 4 = 78.54 mm².")]),
      L("Check the cable", "Cable Lab", "🔬", "Stress", "Intermediate",
        { text: "Stress = force / area (N/mm² is MPa). The factor of safety compares the material's yield strength with the working stress: FS = yield / stress.", code: "stress = F / A\nFS = yield / stress" },
        [A("crane-3", "Cable stress", "Find the stress in MPa when 4905 N acts on 78.54 mm².", "62.45", "stress = F / A. N and mm² give MPa.", "4905 / 78.54 = 62.45 MPa."),
         A("crane-4", "Safety margin", "The cable yields at 250 MPa. Find the factor of safety (1 decimal is fine).", "4", "FS = yield / stress.", "250 / 62.45 ≈ 4.0. Lifting gear needs at least 4, so it just passes.")]),
      L("Power the lift", "Motor Room", "⚙️", "Torque and safety", "Advanced",
        { text: "Torque = force × radius. A good safety check is automated: compute the factor of safety and compare it with the required value.", code: "T = F * r" },
        [A("crane-5", "Drum torque", "The drum radius is 0.1 m and the cable force is 4905 N. Find the torque in N·m.", "490.5", "T = F × r.", "4905 × 0.1 = 490.5 N·m."),
         K("crane-6", "Safety factor check", "Write solve(F, area, yieldStrength) that returns the factor of safety: yieldStrength / (F / area).", "F, area, yieldStrength", [[[4905, 78.54, 250], 4], [[1000, 10, 200], 2], [[2000, 20, 500], 5], [[5000, 50, 100], 1]], "Find the stress first (F / area), then divide the yield strength by it.", ["stress = F / area.", "return yieldStrength / (F / area);"])]),
    ] },
  { id: "footbridge", dept: "civil", icon: "🌉", title: "Campus Footbridge",
    story: "Students need a small footbridge over a drain. Find the loads, design the beam, and plan the concrete deck.",
    levels: [
      L("Find the loads", "Site Office", "📋", "Loads", "Beginner",
        { text: "A uniform load (UDL) is spread along the beam. Total load W = w × L. On a simply supported beam each support carries half.", code: "W = w * L\nR = W / 2" },
        [A("fb-1", "Total load", "A footbridge beam spans 6 m and carries 5 kN/m. Find the total load in kN.", "30", "W = w × L.", "5 × 6 = 30 kN."),
         A("fb-2", "Support reaction", "Find the reaction at each support in kN.", "15", "Each support takes half of the total load.", "30 / 2 = 15 kN.")]),
      L("Design the beam", "Design Desk", "📐", "Beams", "Intermediate",
        { text: "Maximum bending moment of a simply supported beam with UDL: M = wL² / 8. The section modulus needed is Z = M / allowable stress. Convert kN·m to N·mm by multiplying by 10⁶.", code: "M = w * L * L / 8\nZ = M / sigma" },
        [A("fb-3", "Bending moment", "Find the maximum moment M = wL²/8 in kN·m for w = 5 kN/m and L = 6 m.", "22.5", "Square the span first: 6 × 6 = 36.", "5 × 36 / 8 = 22.5 kN·m."),
         A("fb-4", "Section modulus", "The allowable stress is 150 MPa. Find the section modulus Z in mm³ (M = 22.5 × 10⁶ N·mm).", "150000", "Z = M / σ, with M in N·mm.", "22.5 × 10⁶ / 150 = 150000 mm³.")]),
      L("Plan the deck", "Concrete Yard", "🧱", "Quantities", "Advanced",
        { text: "Concrete volume = length × width × thickness. Cost = volume × rate per m³.", code: "V = l * w * d\ncost = V * rate" },
        [A("fb-5", "Deck volume", "The deck is 6 m long, 2 m wide and 0.15 m thick. Find the concrete volume in m³.", "1.8", "V = l × w × d.", "6 × 2 × 0.15 = 1.8 m³."),
         K("fb-6", "Concrete cost", "Write solve(l, w, d, rate) that returns the cost: l × w × d × rate.", "l, w, d, rate", [[[6, 2, 0.15, 5000], 9000], [[1, 1, 1, 100], 100], [[4, 3, 0.2, 4000], 9600]], "Multiply all three sizes first, then the rate.", ["Volume is l * w * d.", "return l * w * d * rate;"])]),
    ] },
  { id: "canteen", dept: "ads", icon: "🍽️", title: "Canteen Rush Predictor",
    story: "The canteen wants to know how many students will come tomorrow. Use data to make a prediction.",
    levels: [
      L("Look at the data", "Data Desk", "📊", "Statistics", "Beginner",
        { text: "Mean = sum ÷ count. Median = the middle value after sorting. They describe a typical value in two different ways.", code: "mean = sum / count\nmedian = middle of sorted list" },
        [A("cn-1", "Average visitors", "Canteen visitors Monday to Friday: 120, 150, 130, 170, 230. Find the mean.", "160", "Add all five and divide by 5.", "800 / 5 = 160."),
         A("cn-2", "Middle day", "Find the median of the same five values.", "150", "Sort them first: 120, 130, 150, 170, 230.", "The middle value is 150.")]),
      L("Spot the pattern", "Pattern Lab", "🔍", "Data insight", "Intermediate",
        { text: "Range = max − min shows how spread out the data is. One unusual value (an outlier) pulls the mean but barely moves the median.", code: "range = max - min" },
        [A("cn-3", "Spread of the data", "Find the range (max − min) of the data.", "110", "Biggest minus smallest.", "230 − 120 = 110."),
         A("cn-4", "Which is typical?", "Friday's 230 was an unusual rush. Which describes a normal day better: mean or median? Type one word.", "median", "Think about which one an outlier pulls away.", "The median stays at 150, while the mean was pulled up to 160 by the rush.", { text: true })]),
      L("Predict tomorrow", "Prediction Room", "🔮", "Prediction", "Advanced",
        { text: "A moving average predicts the next value by averaging the last few values. It is the simplest forecasting model.", code: "prediction = mean(last n values)" },
        [A("cn-5", "Next-day guess", "Predict Saturday as the mean of the last 3 days (130, 170, 230).", "176.67", "Add the three values and divide by 3.", "530 / 3 ≈ 176.67 visitors."),
         K("cn-6", "Moving average", "Write solve(arr, n) that returns the mean of the last n values in arr.", "arr, n", [[[[120, 150, 130, 170, 230], 3], 176.67], [[[10, 20, 30], 2], 25], [[[5], 1], 5], [[[1, 2, 3, 4], 4], 2.5]], "Use slice(-n) to take the last n values.", ["arr.slice(-n) gives the last n values.", "const last = arr.slice(-n); return last.reduce((a, b) => a + b, 0) / n;"])]),
    ] },
];
